admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /panel

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /panel

edubox:
  resource: '@EduBoxBundle/Controller/'
  type: annotation


fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /panel/user/profile

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /panel/user/profile


2fa_login:
  path: /2fa
  defaults:
    _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
  path: /2fa_check