<?php


namespace EduBoxBundle\Controller\Admin;


use Sonata\AdminBundle\Controller\CRUDController;

class HomeworkCRUDController extends CRUDController
{
    public function listAction()
    {
        return parent::listAction(); // TODO: Change the autogenerated stub
    }

    public function createAction()
    {
        return parent::createAction(); // TODO: Change the autogenerated stub
    }

    public function editAction($id = null)
    {
        return parent::editAction($id); // TODO: Change the autogenerated stub
    }

    public function showAction($id = null)
    {
        return parent::showAction($id); // TODO: Change the autogenerated stub
    }

}