<?php

namespace EduBoxBundle\Repository;

/**
 * CallScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
