<?php

namespace EduBoxBundle\Repository;

use EduBoxBundle\Entity\Mark;
use EduBoxBundle\Entity\Setting;

/**
 * MarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByOrCreate(array $criteria)
    {
        $em = $this->getEntityManager();
        $mark = $this->findOneBy($criteria);

        if ($mark === null) {
            $mark = new Mark();
            foreach ($criteria as $key => $value) {
                $setter = 'set'.ucfirst($key);
                $mark->$setter($value);
            }
            $em->persist($mark);
            $em->flush();
        }

        return $mark;
    }
}
