<?php

namespace EduBoxBundle\Repository;

use EduBoxBundle\Entity\Mark;
use EduBoxBundle\Entity\Quarter;

/**
 * QuarterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuarterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByOrCreate(array $criteria)
    {
        $em = $this->getEntityManager();
        $quarter = $this->findOneBy($criteria);

        if ($quarter === null) {
            $quarter = new Quarter();
            foreach ($criteria as $key => $value) {
                $setter = 'set'.ucfirst($key);
                $quarter->$setter($value);
            }
            $em->persist($quarter);
            $em->flush();
        }

        return $quarter;
    }
}
