<?php

namespace EduBoxBundle\Repository;

/**
 * StudentClassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentClassRepository extends \Doctrine\ORM\EntityRepository
{
}
