<?php

namespace EduBoxBundle\Repository;

/**
 * SubjectAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
