<?php

namespace EduBoxBundle\Repository;

/**
 * SubjectScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectSchedulesGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
