<?php

namespace EduBoxBundle\Repository;

use EduBoxBundle\Entity\UserMeta;

/**
 * UserMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMetaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByOrCreate(array $criteria)
    {
        $em = $this->getEntityManager();
        $meta = $this->findOneBy($criteria);

        if ($meta === null) {
            $meta = new UserMeta();
            foreach ($criteria as $key => $value) {
                $setter = 'set'.ucfirst($key);
                $meta->$setter($value);
            }
            $em->persist($meta);
            $em->flush();
        }

        return $meta;
    }
}
