scheb_two_factor:
  security_tokens:
    - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
  google:
    enabled: true
    server_name: Server Name       # Server name used in QR code
    issuer: Issuer Name            # Issuer name used in QR code
    template: security/2fa_form.html.twig   # Template used to render the authentication form